---

mysql_bind_address: "0.0.0.0"
mysql_port: 3306

# Default MEDIUM policy adds the conditions that passwords must contain at least 1 numeric character,
# 1 lowercase character, 1 uppercase character, and 1 special (nonalphanumeric) character.
mysql_root_pass: root
