---
galaxy_info:
  author: Artem Shorokhov
  description: MySQL server installation.
  license: BSD
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags:
    - database
    - mysql

dependencies: []
